# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd4f14cc0c981d5734dd4ce8260b779b5763202edab75e1426be35b68602647c668808e536f59c494c0fc535c30fb704575e5b5b065ad60a8d4457c74b232555

test:
  secret_key_base: 5e9014567d39691ebd798ee924095272ec36f2279fc2985bcec411184be3247fa15fd7f05a15cbd546d15b0c365e72ee90dde238e46f96eb25f1ac9c3323a4bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
